name: Distribute

on:
  push:
    branches: [master, develop, beta]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore Dispatch\Dispatch.sln

      - name: Build the Solution (Develop)
        if: github.ref == 'refs/heads/develop'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }} /p:DefineConstants=DEVELOP

      - name: Build the Solution (Beta)
        if: github.ref == 'refs/heads/beta'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }} /p:DefineConstants=BETA

      - name: Build the Solution (Master)
        if: github.ref == 'refs/heads/master'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }}

      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Package Setup
        run: iscc Setup\script.iss

      - name: Archive Setup
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: Setup\Output\

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Setup
        uses: actions/download-artifact@v2
        with:
          name: setup

      - name: Write Files
        run: |
          NAME=$(ls | grep '.exe' | head -1)
          VERSION=$(echo $NAME | egrep -o '[0-9]+.[0-9]+.[0-9]+.[0-9]+')
          DATE=$(date -u +%FT%TZ)
          FORMAT='{ "name": "%s", "version": "%s", "date": "%s" }\n'
          printf "$FORMAT" "$NAME" "$VERSION" "$DATE" > latest.json

      - name: Upload to Azure (Develop)
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        if: github.ref == 'refs/heads/develop'
        with:
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          container_name: develop
          source_folder: .

      - name: Upload to Azure (Beta)
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        if: github.ref == 'refs/heads/beta'
        with:
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          container_name: beta
          source_folder: .

      - name: Upload to Azure (Master)
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        if: github.ref == 'refs/heads/master'
        with:
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          container_name: master
          source_folder: .
