name: Distribute

on:
  push:
    branches: [develop, beta, main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore Dispatch\Dispatch.sln

      - name: Build the Solution (Develop)
        if: github.ref == 'refs/heads/develop'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }} /p:DefineConstants=NIGHTLY

      - name: Build the Solution (Beta)
        if: github.ref == 'refs/heads/beta'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }} /p:DefineConstants=BETA

      - name: Build the Solution (Main)
        if: github.ref == 'refs/heads/main'
        run: msbuild Dispatch\Dispatch.sln /p:Configuration=Release /p:Revision=${{ github.run_number }}

      - name: Sign Application
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERT_BASE64 }}'
          folder: 'Dispatch\Dispatch\bin\Release\'
          recursive: true

      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Package Setup (Develop)
        if: github.ref == 'refs/heads/develop'
        run: iscc /DMyAppChannel=Nightly Setup\script.iss

      - name: Package Setup (Beta)
        if: github.ref == 'refs/heads/beta'
        run: iscc /DMyAppChannel=Beta Setup\script.iss

      - name: Package Setup (Main)
        if: github.ref == 'refs/heads/main'
        run: iscc Setup\script.iss

      - name: Sign Setup
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERT_BASE64 }}'
          folder: 'Setup\Output\'
          recursive: true

      - name: Archive Setup
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: Setup\Output\

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Setup
        uses: actions/download-artifact@v2
        with:
          name: setup

      - name: Set Container Name (Develop)
        if: github.ref == 'refs/heads/develop'
        run: echo 'CONTAINER_NAME=nightly' >> $GITHUB_ENV

      - name: Set Container Name (Beta)
        if: github.ref == 'refs/heads/beta'
        run: echo 'CONTAINER_NAME=beta' >> $GITHUB_ENV

      - name: Set Container Name (Main)
        if: github.ref == 'refs/heads/main'
        run: echo 'CONTAINER_NAME=stable' >> $GITHUB_ENV

      - name: Set Release Name and Version
        run: |
          NAME=$(ls | grep '.exe' | head -1)
          VERSION=$(echo $NAME | egrep -o '[0-9]+.[0-9]+.[0-9]+')
          echo "SETUP_NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Variant (Develop)
        if: github.ref == 'refs/heads/develop'
        run: echo VARIANT=nightly >> $GITHUB_ENV

      - name: Set Variant (Beta)
        if: github.ref == 'refs/heads/beta'
        run: echo VARIANT=beta >> $GITHUB_ENV

      - name: Next Build Number Action
        uses: ./.github/actions/next-build-number
        id: next_build_number
        with:
          format: '${{ env.VERSION }}-${{ env.VARIANT }}\.(\d+)'

      - name: Create Release (Develop)
        id: create_release_develop
        if: github.ref == 'refs/heads/develop'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}-${{ env.VARIANT }}.${{ steps.next_build_number.outputs.next }}
          release_name: ${{ env.VERSION }}-${{ env.VARIANT }}.${{ steps.next_build_number.outputs.next }}
          draft: false
          prerelease: true

      - name: Create Release (Beta)
        id: create_release_beta
        if: github.ref == 'refs/heads/beta'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}-${{ env.VARIANT }}.${{ steps.next_build_number.outputs.next }}
          release_name: ${{ env.VERSION }}-${{ env.VARIANT }}.${{ steps.next_build_number.outputs.next }}
          draft: false
          prerelease: true

      - name: Create Release (Main)
        id: create_release_main
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Develop)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_develop.outputs.upload_url }}
          asset_path: ./${{ env.SETUP_NAME }}
          asset_name: setup.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Beta)
        if: github.ref == 'refs/heads/beta'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_beta.outputs.upload_url }}
          asset_path: ./${{ env.SETUP_NAME }}
          asset_name: setup.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_main.outputs.upload_url }}
          asset_path: ./${{ env.SETUP_NAME }}
          asset_name: setup.exe
          asset_content_type: application/octet-stream
